export enum ChessPieceStartIndexes {
  LeftWhiteRook = 0,
  LeftWhiteKnight = 1,
  LeftWhiteBishop = 2,
  WhiteQueen = 3,
  WhiteKing = 4,
  RightWhiteBishop = 5,
  RightWhiteKnight = 6,
  RightWhiteRook = 7,
  RightBlackRook = 56,
  RightBlackKnight = 57,
  RightBlackBishop = 58,
  BlackKing = 59,
  BlackQueen = 60,
  LeftBlackBishop = 61,
  LeftBlackKnight = 62,
  LeftBlackRook = 63,
}
